# Generated by Django 4.1.2 on 2023-09-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MachineIssueReportSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Resolved'), (2, 'Urgent'), (3, 'Close')]),
        ),
        migrations.AlterField(
            model_name='issuestatushistory',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Resolved'), (2, 'Urgent'), (3, 'Close')]),
        ),
    ]
